version: "3"
services:
  node:
    build: .
    ports:
      - "3000:3000"
    tty: true
    volumes: 
      - ~/.ssh:/home/node/.ssh
      - ~/.gitconfig:/home/node/.gitconfig
      - ~/.bash_history:/home/node/.bash_history
    networks:
      - dockerconnet
networks: 
  dockerconnet:
    external: true
